### ISSUE TITLE
Flutter action comparison

### ISSUE THREAD

**Issue by awhitford** [steebchen/flutter#10]
Could you explain how this differs from the _more popular_ [Flutter action](https://github.com/marketplace/actions/flutter-action).  Is this faster? Is this more or less flexible? Pros/cons?

**Comment by steebchen** [comment]
I built this for my own needs originally, I believe your linked action did not exist back then. I think you should probably use the other action, since this one is not maintained and you can't select specific versions.

**Comment by awhitford** [comment]
That's good advice. Thank you.
