### ISSUE TITLE
Flutter version is not upto date.

### ISSUE THREAD

**Issue by Poujhit** [steebchen/flutter#11]
In the build logs, it says there is a new update available for the flutter sdk. Do update the SDK.
![Screenshot 2020-11-19 150428](https://user-images.githubusercontent.com/55449207/99648064-9e95ed80-2a78-11eb-9fa1-995bd7671b4b.png)

**Comment by steebchen** [comment]
Please use this package https://github.com/subosito/flutter-action, it's more flexible and actually maintained.
