### ISSUE TITLE
Failed to build APK due to a failure to read the path 

### ISSUE THREAD

**Issue by adar2378** [steebchen/flutter#4]
Hi, I'm trying to build my apk. Tests work fine. But when building it says it could find the path of the .dart file :( But it works fine on my machine 😛 Can you have a look in the log?

1m 31s
##[error]Docker run failed with exit code 1
Run steebchen/flutter@v1.0.0
/usr/bin/docker run --name f6cdeb67f866cc285c4f0f8bcbb40097626e3d_8c47a3 --label f6cdeb --workdir /github/workspace --rm -e INPUT_ARGS -e HOME -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e GITHUB_ACTIONS=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/AssetTracker/AssetTracker":"/github/workspace" f6cdeb:67f866cc285c4f0f8bcbb40097626e3d build apk --release
You are building a fat APK that includes binaries for android-arm, android-arm64.
If you are deploying the app to the Play Store, it's recommended to use app bundles or split the APK to reduce the APK size.
    To generate an app bundle, run:
        flutter build appbundle --target-platform android-arm,android-arm64
        Learn more on: https://developer.android.com/guide/app-bundle
    To split the APKs per ABI, run:
        flutter build apk --target-platform android-arm,android-arm64 --split-per-abi
        Learn more on:  https://developer.android.com/studio/build/configure-apk-splits#configure-abi-split
Initializing gradle...                                              7.0s
Resolving dependencies...                                          62.6s
Running Gradle task 'assembleRelease'...                        

Compiler message:

lib/routes.dart:4:8: Error: Error when reading 'lib/views/assignee/add_new_assignee_screen.dart': No such file or directory

import 'package:keyassettest/views/assignee/add_new_assignee_screen.dart';

       ^

**Comment by steebchen** [comment]
It's unlikely that this issue is specific to the Github Action. I suggest you try it with the docker image this action uses (`gableroux/flutter`), if you can reproduce the problem there it's out of scope.

**Comment by adar2378** [comment]
ooh I see, thanks
